[project]
name = "textanalysis-tool-hartman"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.0",
    "ebooklib>=0.19",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
